Feat/end user/login
Awrmani/AutoQuotes pull request #115
Opened 2023-03-05 16:32 UTC by VanHoanTran

close #30

2023-03-05 21:15 UTC, ghost requested changes

2023-03-05 21:15 UTC, ghost commented on packages/end-user-fe/src/sagas/index.js
This will not let me set this note on lne 35, but the correct syntax is:
onSuccess: [[earlySetToken], [refreshCurrentUser], apiCall.DISPATCH_SUCCESS];
(there are two nested arrays at max, contents of the outer array runs in sequence, while contents of the inner one run in parallel)

2023-03-05 21:15 UTC, ghost commented on packages/end-user-fe/src/components/EndUserLogin/index.js
> +                '&:hover': { cursor: 'pointer' },
No need for the '&hover' as `cursor: pointer;` always relates to the hover state

2023-03-06 01:04 UTC, Awrmani approved these changes

2023-03-06 01:55 UTC, VanHoanTran commented on packages/end-user-fe/src/sagas/index.js
it is quite advanced to me. I will try to get them.

2023-03-06 01:58 UTC, VanHoanTran commented on packages/end-user-fe/src/components/EndUserLogin/index.js
> +                '&:hover': { cursor: 'pointer' },
When we don't provide the href attribute. it will not be a pointer when I hover the text. That's why I add the hover. whether I make something wrong here.

2023-03-06 02:25 UTC, VanHoanTran commented on packages/end-user-fe/src/components/EndUserLogin/index.js
> +                '&:hover': { cursor: 'pointer' },
I see what you mean.  so I still need to keep `cursor: pointer`. But, I can remove the `&.hover`

2023-03-06 13:25 UTC, ghost requested changes

2023-03-06 13:25 UTC, ghost commented on packages/end-user-fe/src/paths.js
> +const profile = ({ id = ':id' } = {}) => ({
No need for this ID :)

2023-03-06 18:43 UTC, ghost approved these changes

2023-03-06 19:08 UTC, ghost approved these changes

2023-03-06 19:27 UTC, merged