Feature/dashbroad UI
Awrmani/AutoQuotes pull request #84
Opened 2023-02-07 03:51 UTC by VanHoanTran

it is not functional yet. I have to fix it when I get back-end API and decide paths for each functionality such as inventory or service. should we merge it to develop branch

2023-02-07 14:09 UTC, ghost requested changes

2023-02-07 14:09 UTC, ghost commented on packages/mechanic-shop-fe/src/components/ShopLayout/index.js
> +      <SideBar></SideBar>
```suggestion
      <SideBar/>
```

2023-02-07 14:09 UTC, ghost commented on packages/mechanic-shop-fe/src/components/ShopLayout/SideBar/index.js
> +  const drawer = (
Please make this it's own component, I.e.,  SideBarInner

2023-02-07 14:09 UTC, ghost commented on packages/mechanic-shop-fe/src/components/ShopLayout/SideBar/index.js
> +  };
Please memoize this

In this solution, sideBarProps is regenerated every time the component is rendered which is bad for performance. Please move this const above the SideBar component so it is generated only once

2023-02-07 14:09 UTC, ghost commented on packages/mechanic-shop-fe/src/screens/ShopDashboardScreen.js
> +  return ShopLayout;
Layout is rendered by the `react-router`. No need to put it here. Please revert this file

2023-02-09 00:59 UTC, VanHoanTran commented on packages/mechanic-shop-fe/src/components/ShopLayout/SideBar/index.js
> +  const drawer = (
I just made some changes based on your comments. Thank you.

2023-02-09 01:02 UTC, VanHoanTran commented on packages/mechanic-shop-fe/src/components/ShopLayout/SideBar/index.js
> +  };
Can you explain what will happen if I move it out of the function?

2023-02-09 14:10 UTC, ghost commented on packages/mechanic-shop-fe/src/components/ShopLayout/SideBar/index.js
> +  };
Sure!

All react components that you create, (since these are functional components, they are all essentially JavaScript functions) like SideBarInner, are called every time React wants to update them. If you put the above object inside that function, it will too be generated over and over again every time the function is called.

Stuff that are around the functional components (I.e. this object now) are only generated once, when the application starts up. They will work just the same, but the application will be faster (and you can avoid a lot of other issues, too)

2023-02-09 14:10 UTC, ghost approved these changes

2023-02-09 14:11 UTC, ghost commented
Approved, please squash and merge it

2023-02-09 14:21 UTC, VanHoanTran commented on packages/mechanic-shop-fe/src/components/ShopLayout/SideBar/index.js
> +  };
thank you for the clarification

2023-02-09 14:23 UTC, merged