Feature/inventory
Awrmani/AutoQuotes pull request #91
Opened 2023-02-13 20:20 UTC by VanHoanTran

Closes #13 
Closes #14 
Closes #15 
Closes #16

2023-02-13 22:45 UTC, ghost commented
Hey @VanHoanTran Could you please
- git fetch
- git merge origin/develop

resolve the conflicts, add everything to "staged"
- git merge --continue
- git push

Please?
Your branch has a bunch of conflicts compared to `develop` because a lot has been changed there since this branch was opened

Let me know if you need help with this

2023-02-14 02:44 UTC, VanHoanTran commented
> Hey @VanHoanTran Could you please
> 
> * git fetch
> * git merge origin/develop
> 
> resolve the conflicts, add everything to "staged"
> 
> * git merge --continue
> * git push
> 
> Please? Your branch has a bunch of conflicts compared to `develop` because a lot has been changed there since this branch was opened
> 
> Let me know if you need help with this

@dadolhay, I already solved conflicts. please check it out. thank you

2023-02-14 03:42 UTC, ghost requested changes
Only some minor naming changes

Amazing work!!

2023-02-14 03:42 UTC, ghost commented on packages/mechanic-shop-fe/src/Routes.js
> +            element={<InventoryScreen />}
We call these "parts"
(we merged inventory into parts at the end of last term)

So please use names like:
-PartList / PartListScreen
-EditPartForm

-EditPartScreen (can use EditPartForm)
-AddPartScreen (can also use EditPartForm)

2023-02-14 05:30 UTC, VanHoanTran commented on packages/mechanic-shop-fe/src/Routes.js
> +            element={<InventoryScreen />}
I changed all the pathnames and components. Let me know if anything needs to be changed. I have not completed how to display a single part in the addPartForm. I will do it as soon as I can

2023-02-14 19:40 UTC, ghost requested changes
A few minor changes only.

2023-02-14 19:40 UTC, ghost commented on packages/mechanic-shop-fe/src/Routes.js
> +            path={paths.addPartForm().pathname}
Please call this addPart

2023-02-14 19:40 UTC, ghost commented on packages/mechanic-shop-fe/src/Routes.js
> +            path={paths.editPartForm().pathname}
Please call this editPart

2023-02-14 19:40 UTC, ghost commented on packages/mechanic-shop-fe/src/constants/actionTypes.js
> +export const ADD_ITEM = 'ADD_ITEM';
Redux convention sais to use this as `noun(s)_verb` (verb at the end)

Please use the PART_ADD name

2023-02-14 19:40 UTC, ghost commented on packages/mechanic-shop-fe/src/actions/index.js
> +export const addItem = createAction(actionTypes.ADD_ITEM);
Please use the name addPart

2023-02-14 19:40 UTC, ghost commented on packages/mechanic-shop-fe/src/components/EditPartForm/index.js
> +      <CssBaseline />
CssBaseLine tries to reset the css of external libraries. We don't have any external libraries messing with our CSS system, so this is not needed

2023-02-14 19:40 UTC, ghost commented on packages/mechanic-shop-fe/src/paths.js
> +const addPartForm = () => ({
Please rename to addPart

2023-02-14 19:40 UTC, ghost commented on packages/mechanic-shop-fe/src/paths.js
> +const editPartForm = () => ({
please rename to editPart

2023-02-14 19:40 UTC, ghost commented on packages/mechanic-shop-fe/src/Routes.js
> +            element={<InventoryScreen />}
Thanks, I created some comments around naming

2023-02-16 03:48 UTC, ghost approved these changes
Very cool, hats off!

2023-02-16 04:29 UTC, merged